import type { Metadata } from "next";

import "./globals.css";
import Body from "./body";
import { FC, ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <Body>{children}</Body>
    </html>
  );
};

export default RootLayout;
